// Local private PANACEA includes
#include "type_map.hpp"

#include "attributes/covariance.hpp"
#include "attributes/covariance/covariance_correlated.hpp"
#include "attributes/covariance/covariance_uncorrelated.hpp"
#include "attributes/reduced_covariance.hpp"
#include "attributes/reduced_inv_covariance.hpp"
#include "kernels/base_kernel_wrapper.hpp"
#include "kernels/kernel_specifications.hpp"
#include "matrix/matrix.hpp"
#include "primitives/primitive.hpp"
#include "primitives/primitive_group.hpp"
#include "vector/vector.hpp"

// Public PANACEA includes
#include "panacea/base_descriptor_wrapper.hpp"
#include "panacea/entropy_term.hpp"

// Standard includes
#include <deque>
#include <string>
#include <unordered_map>
#include <vector>

namespace panacea {

const std::unordered_map<std::type_index, std::string> type_map{
    {std::type_index(typeid(std::vector<double>)), "std::vector<double>"},
    {std::type_index(typeid(std::vector<double> &)), "std::vector<double> &"},
    {std::type_index(typeid(std::vector<double> *)), "std::vector<double>*"},
    {std::type_index(typeid(std::vector<std::vector<double>>)),
     "std::vector<std::vector<double>>"},
    {std::type_index(typeid(std::vector<std::vector<double>> &)),
     "std::vector<std::vector<double>> &"},
    {std::type_index(typeid(std::vector<std::vector<double>> *)),
     "std::vector<std::vector<double>>*"},
    {std::type_index(typeid(double *)), "double *"},
    {std::type_index(typeid(double **)), "double **"},
    {std::type_index(typeid(double ***)), "double ***"},
    {std::type_index(typeid(std::vector<std::deque<double>>)),
     "std::vector<std::deque<double>>"},
    {std::type_index(typeid(std::vector<std::deque<double>> &)),
     "std::vector<std::deque<double>> &"},
    {std::type_index(typeid(BaseKernelWrapper *)), "BaseKernelWrapper *"},
    {std::type_index(typeid(BaseKernelWrapper &)), "BaseKernelWrapper &"},
    {std::type_index(typeid(BaseKernelWrapper)), "BaseKernelWrapper"},
    {std::type_index(typeid(BaseDescriptorWrapper *)),
     "BaseDescriptorWrapper *"},
    {std::type_index(typeid(BaseDescriptorWrapper &)),
     "BaseDescriptorWrapper &"},
    {std::type_index(typeid(BaseDescriptorWrapper)), "BaseDescriptorWrapper"},
    {std::type_index(typeid(Matrix *)), "Matrix *"},
    {std::type_index(typeid(Matrix &)), "Matrix &"},
    {std::type_index(typeid(Matrix)), "Matrix"},
    {std::type_index(typeid(Vector *)), "Vector *"},
    {std::type_index(typeid(Vector &)), "Vector &"},
    {std::type_index(typeid(Vector)), "Vector"},
    {std::type_index(typeid(Covariance *)), "Covariance *"},
    {std::type_index(typeid(Covariance &)), "Covariance &"},
    {std::type_index(typeid(Covariance)), "Covariance"},
    {std::type_index(typeid(CovarianceCorrelated *)), "CovarianceCorrelated *"},
    {std::type_index(typeid(CovarianceCorrelated &)), "CovarianceCorrelated &"},
    {std::type_index(typeid(CovarianceCorrelated)), "CovarianceCorrelated"},
    {std::type_index(typeid(CovarianceUncorrelated *)),
     "CovarianceUncorrelated *"},
    {std::type_index(typeid(CovarianceUncorrelated &)),
     "CovarianceUncorrelated &"},
    {std::type_index(typeid(CovarianceUncorrelated)), "CovarianceUncorrelated"},
    {std::type_index(typeid(ReducedCovariance *)), "ReducedCovariance *"},
    {std::type_index(typeid(ReducedCovariance &)), "ReducedCovariance &"},
    {std::type_index(typeid(ReducedCovariance)), "ReducedCovariance"},
    {std::type_index(typeid(ReducedInvCovariance *)), "ReducedInvCovariance *"},
    {std::type_index(typeid(ReducedInvCovariance &)), "ReducedInvCovariance &"},
    {std::type_index(typeid(ReducedInvCovariance)), "ReducedInvCovariance"},
    {std::type_index(typeid(KernelSpecification)), "KernelSpecification"},
    {std::type_index(typeid(KernelSpecification *)), "KernelSpecification *"},
    {std::type_index(typeid(KernelSpecification &)), "KernelSpecification &"},
    {std::type_index(typeid(Primitive *)), "Primitive *"},
    {std::type_index(typeid(Primitive &)), "Primitive &"},
    {std::type_index(typeid(Primitive)), "Primitive"},
    {std::type_index(typeid(EntropyTerm *)), "EntropyTerm *"},
    {std::type_index(typeid(EntropyTerm &)), "EntropyTerm &"},
    {std::type_index(typeid(EntropyTerm)), "EntropyTerm"},
    {std::type_index(typeid(PrimitiveGroup *)), "PrimitiveGroup *"},
    {std::type_index(typeid(PrimitiveGroup &)), "PrimitiveGroup &"},
    {std::type_index(typeid(PrimitiveGroup)), "PrimitiveGroup"},

    {std::type_index(typeid(std::unique_ptr<std::vector<double>>)),
     "std::unique_ptr<std::vector<double>>"},
    {std::type_index(typeid(std::unique_ptr<std::vector<std::vector<double>>>)),
     "std::unique_ptr<std::vector<std::vector<double>>>"},
    {std::type_index(typeid(std::unique_ptr<double *>)),
     "std::unique_ptr<double *>"},
    {std::type_index(typeid(std::unique_ptr<double **>)),
     "std::unique_ptr<double **>"},
    {std::type_index(typeid(std::unique_ptr<double ***>)),
     "std::unique_ptr<double ***>"},
    {std::type_index(typeid(std::unique_ptr<std::vector<std::deque<double>>>)),
     "std::unique_ptr<std::vector<std::deque<double>>>"},
    {std::type_index(typeid(std::unique_ptr<BaseKernelWrapper>)),
     "std::unique_ptr<BaseKernelWrapper>"},
    {std::type_index(typeid(std::unique_ptr<BaseDescriptorWrapper>)),
     "std::unique_ptr<BaseDescriptorWrapper>"},
    {std::type_index(typeid(std::unique_ptr<Matrix>)),
     "std::unique_ptr<Matrix>"},
    {std::type_index(typeid(std::unique_ptr<Vector>)),
     "std::unique_ptr<Vector>"},
    {std::type_index(typeid(std::unique_ptr<Covariance>)),
     "std::unique_ptr<Covariance>"},
    {std::type_index(typeid(std::unique_ptr<CovarianceCorrelated>)),
     "std::unique_ptr<CovarianceCorrelated>"},
    {std::type_index(typeid(std::unique_ptr<CovarianceUncorrelated>)),
     "std::unique_ptr<CovarianceUncorrelated>"},
    {std::type_index(typeid(std::unique_ptr<ReducedCovariance>)),
     "std::unique_ptr<ReducedCovariance>"},
    {std::type_index(typeid(std::unique_ptr<ReducedInvCovariance>)),
     "std::unique_ptr<ReducedInvCovariance>"},
    {std::type_index(typeid(std::unique_ptr<KernelSpecification>)),
     "std::unique_ptr<KernelSpecification>"},
    {std::type_index(typeid(std::unique_ptr<Primitive>)),
     "std::unique_ptr<Primitive>"},
    {std::type_index(typeid(std::unique_ptr<EntropyTerm>)),
     "std::unique_ptr<EntropyTerm>"},
    {std::type_index(typeid(std::unique_ptr<PrimitiveGroup>)),
     "std::unique_ptr<PrimitiveGroup>"},

    {std::type_index(typeid(std::unique_ptr<std::vector<double>> *)),
     "std::unique_ptr<std::vector<double>> *"},
    {std::type_index(
         typeid(std::unique_ptr<std::vector<std::vector<double>>> *)),
     "std::unique_ptr<std::vector<std::vector<double>>> *"},
    {std::type_index(typeid(std::unique_ptr<double *> *)),
     "std::unique_ptr<double *> *"},
    {std::type_index(typeid(std::unique_ptr<double **> *)),
     "std::unique_ptr<double **> *"},
    {std::type_index(typeid(std::unique_ptr<double ***> *)),
     "std::unique_ptr<double ***> *"},
    {std::type_index(
         typeid(std::unique_ptr<std::vector<std::deque<double>>> *)),
     "std::unique_ptr<std::vector<std::deque<double>>> *"},
    {std::type_index(typeid(std::unique_ptr<BaseKernelWrapper> *)),
     "std::unique_ptr<BaseKernelWrapper> *"},
    {std::type_index(typeid(std::unique_ptr<BaseDescriptorWrapper> *)),
     "std::unique_ptr<BaseDescriptorWrapper> *"},
    {std::type_index(typeid(std::unique_ptr<Matrix> *)),
     "std::unique_ptr<Matrix> *"},
    {std::type_index(typeid(std::unique_ptr<Vector> *)),
     "std::unique_ptr<Vector> *"},
    {std::type_index(typeid(std::unique_ptr<Covariance> *)),
     "std::unique_ptr<Covariance> *"},
    {std::type_index(typeid(std::unique_ptr<CovarianceCorrelated> *)),
     "std::unique_ptr<CovarianceCorrelated> *"},
    {std::type_index(typeid(std::unique_ptr<CovarianceUncorrelated> *)),
     "std::unique_ptr<CovarianceUncorrelated> *"},
    {std::type_index(typeid(std::unique_ptr<ReducedCovariance> *)),
     "std::unique_ptr<ReducedCovariance> *"},
    {std::type_index(typeid(std::unique_ptr<ReducedInvCovariance> *)),
     "std::unique_ptr<ReducedInvCovariance> *"},
    {std::type_index(typeid(std::unique_ptr<KernelSpecification> *)),
     "std::unique_ptr<KernelSpecification> *"},
    {std::type_index(typeid(std::unique_ptr<Primitive> *)),
     "std::unique_ptr<Primitive> *"},
    {std::type_index(typeid(std::unique_ptr<EntropyTerm> *)),
     "std::unique_ptr<EntropyTerm> *"},
    {std::type_index(typeid(std::unique_ptr<PrimitiveGroup> *)),
     "std::unique_ptr<PrimitiveGroup> *"},

    {std::type_index(typeid(const std::unique_ptr<std::vector<double>>)),
     "const std::unique_ptr<std::vector<double>>"},
    {std::type_index(
         typeid(const std::unique_ptr<std::vector<std::vector<double>>>)),
     "const std::unique_ptr<std::vector<std::vector<double>>>"},
    {std::type_index(typeid(const std::unique_ptr<double *>)),
     "const std::unique_ptr<double *>"},
    {std::type_index(typeid(const std::unique_ptr<double **>)),
     "const std::unique_ptr<double **>"},
    {std::type_index(typeid(const std::unique_ptr<double ***>)),
     "const std::unique_ptr<double ***>"},
    {std::type_index(
         typeid(const std::unique_ptr<std::vector<std::deque<double>>>)),
     "const std::unique_ptr<std::vector<std::deque<double>>>"},
    {std::type_index(typeid(const std::unique_ptr<BaseKernelWrapper>)),
     "const std::unique_ptr<BaseKernelWrapper>"},
    {std::type_index(typeid(const std::unique_ptr<BaseDescriptorWrapper>)),
     "const std::unique_ptr<BaseDescriptorWrapper>"},
    {std::type_index(typeid(const std::unique_ptr<Matrix>)),
     "const std::unique_ptr<Matrix>"},
    {std::type_index(typeid(const std::unique_ptr<Vector>)),
     "const std::unique_ptr<Vector>"},
    {std::type_index(typeid(const std::unique_ptr<Covariance>)),
     "const std::unique_ptr<Covariance>"},
    {std::type_index(typeid(const std::unique_ptr<CovarianceCorrelated>)),
     "const std::unique_ptr<CovarianceCorrelated>"},
    {std::type_index(typeid(const std::unique_ptr<CovarianceUncorrelated>)),
     "const std::unique_ptr<CovarianceUncorrelated>"},
    {std::type_index(typeid(const std::unique_ptr<ReducedCovariance>)),
     "const std::unique_ptr<ReducedCovariance>"},
    {std::type_index(typeid(const std::unique_ptr<ReducedInvCovariance>)),
     "const std::unique_ptr<ReducedInvCovariance>"},
    {std::type_index(typeid(const std::unique_ptr<KernelSpecification>)),
     "const std::unique_ptr<KernelSpecification>"},
    {std::type_index(typeid(const std::unique_ptr<Primitive>)),
     "const std::unique_ptr<Primitive>"},
    {std::type_index(typeid(const std::unique_ptr<EntropyTerm>)),
     "const std::unique_ptr<EntropyTerm>"},
    {std::type_index(typeid(const std::unique_ptr<PrimitiveGroup>)),
     "const std::unique_ptr<PrimitiveGroup>"},

    {std::type_index(typeid(const std::unique_ptr<std::vector<double>> *)),
     "const std::unique_ptr<std::vector<double>> *"},
    {std::type_index(
         typeid(const std::unique_ptr<std::vector<std::vector<double>>> *)),
     "const std::unique_ptr<std::vector<std::vector<double>>> *"},
    {std::type_index(typeid(const std::unique_ptr<double *> *)),
     "const std::unique_ptr<double *> *"},
    {std::type_index(typeid(const std::unique_ptr<double **> *)),
     "const std::unique_ptr<double **> *"},
    {std::type_index(typeid(const std::unique_ptr<double ***> *)),
     "const std::unique_ptr<double ***> *"},
    {std::type_index(
         typeid(const std::unique_ptr<std::vector<std::deque<double>>> *)),
     "const std::unique_ptr<std::vector<std::deque<double>>> *"},
    {std::type_index(typeid(const std::unique_ptr<BaseKernelWrapper> *)),
     "const std::unique_ptr<BaseKernelWrapper> *"},
    {std::type_index(typeid(const std::unique_ptr<BaseDescriptorWrapper> *)),
     "const std::unique_ptr<BaseDescriptorWrapper> *"},
    {std::type_index(typeid(const std::unique_ptr<Matrix> *)),
     "const std::unique_ptr<Matrix> *"},
    {std::type_index(typeid(const std::unique_ptr<Vector> *)),
     "const std::unique_ptr<Vector> *"},
    {std::type_index(typeid(const std::unique_ptr<Covariance> *)),
     "const std::unique_ptr<Covariance> *"},
    {std::type_index(typeid(const std::unique_ptr<CovarianceCorrelated> *)),
     "const std::unique_ptr<CovarianceCorrelated> *"},
    {std::type_index(typeid(const std::unique_ptr<CovarianceUncorrelated> *)),
     "const std::unique_ptr<CovarianceUncorrelated> *"},
    {std::type_index(typeid(const std::unique_ptr<ReducedCovariance> *)),
     "const std::unique_ptr<ReducedCovariance> *"},
    {std::type_index(typeid(const std::unique_ptr<ReducedInvCovariance> *)),
     "const std::unique_ptr<ReducedInvCovariance> *"},
    {std::type_index(typeid(const std::unique_ptr<KernelSpecification> *)),
     "const std::unique_ptr<KernelSpecification> *"},
    {std::type_index(typeid(const std::unique_ptr<Primitive> *)),
     "const std::unique_ptr<Primitive> *"},
    {std::type_index(typeid(const std::unique_ptr<EntropyTerm> *)),
     "const std::unique_ptr<EntropyTerm> *"},
    {std::type_index(typeid(const std::unique_ptr<PrimitiveGroup> *)),
     "const std::unique_ptr<PrimitiveGroup> *"},

    {std::type_index(typeid(const std::vector<double>)),
     "const std::vector<double>"},
    {std::type_index(typeid(const std::vector<double> &)),
     "const std::vector<double> &"},
    {std::type_index(typeid(const std::vector<double> *)),
     "const std::vector<double>*"},
    {std::type_index(typeid(const std::vector<std::vector<double>>)),
     "const std::vector<std::vector<double>>"},
    {std::type_index(typeid(const std::vector<std::vector<double>> &)),
     "const std::vector<std::vector<double>> &"},
    {std::type_index(typeid(const std::vector<std::vector<double>> *)),
     "const std::vector<std::vector<double>>*"},
    {std::type_index(typeid(const double *)), "const double *"},
    {std::type_index(typeid(const double **)), "const double **"},
    {std::type_index(typeid(const double ***)), "const double ***"},
    {std::type_index(typeid(const std::vector<std::deque<double>>)),
     "const std::vector<std::deque<double>>"},
    {std::type_index(typeid(const std::vector<std::deque<double>> *)),
     "const std::vector<std::deque<double>> *"},
    {std::type_index(typeid(const std::vector<std::deque<double>> &)),
     "const std::vector<std::deque<double>> &"},
    {std::type_index(typeid(const BaseKernelWrapper *)),
     "const BaseKernelWrapper *"},
    {std::type_index(typeid(const BaseKernelWrapper &)),
     "const BaseKernelWrapper &"},
    {std::type_index(typeid(const BaseKernelWrapper)),
     "const BaseKernelWrapper"},
    {std::type_index(typeid(const BaseDescriptorWrapper *)),
     "const BaseDescriptorWrapper *"},
    {std::type_index(typeid(const BaseDescriptorWrapper &)),
     "const BaseDescriptorWrapper &"},
    {std::type_index(typeid(const BaseDescriptorWrapper)),
     "const BaseDescriptorWrapper"},
    {std::type_index(typeid(const Matrix *)), "const Matrix *"},
    {std::type_index(typeid(const Matrix &)), "const Matrix &"},
    {std::type_index(typeid(const Matrix)), "const Matrix"},
    {std::type_index(typeid(const Vector *)), "const Vector *"},
    {std::type_index(typeid(const Vector &)), "const Vector &"},
    {std::type_index(typeid(const Vector)), "const Vector"},
    {std::type_index(typeid(const Covariance *)), "const Covariance *"},
    {std::type_index(typeid(const Covariance &)), "const Covariance &"},
    {std::type_index(typeid(const Covariance)), "const Covariance"},
    {std::type_index(typeid(const CovarianceCorrelated *)),
     "const CovarianceCorrelated *"},
    {std::type_index(typeid(const CovarianceCorrelated &)),
     "const CovarianceCorrelated &"},
    {std::type_index(typeid(const CovarianceCorrelated)),
     "const CovarianceCorrelated"},
    {std::type_index(typeid(const CovarianceUncorrelated *)),
     "const CovarianceUncorrelated *"},
    {std::type_index(typeid(const CovarianceUncorrelated &)),
     "const CovarianceUncorrelated &"},
    {std::type_index(typeid(const CovarianceUncorrelated)),
     "const CovarianceUncorrelated"},
    {std::type_index(typeid(const ReducedCovariance *)),
     "const ReducedCovariance *"},
    {std::type_index(typeid(const ReducedCovariance &)),
     "const ReducedCovariance &"},
    {std::type_index(typeid(const ReducedCovariance)),
     "const ReducedCovariance"},
    {std::type_index(typeid(const ReducedInvCovariance *)),
     "const ReducedInvCovariance *"},
    {std::type_index(typeid(const ReducedInvCovariance &)),
     "const ReducedInvCovariance &"},
    {std::type_index(typeid(const ReducedInvCovariance)),
     "const ReducedInvCovariance"},
    {std::type_index(typeid(const KernelSpecification)),
     "const KernelSpecification"},
    {std::type_index(typeid(const KernelSpecification &)),
     "const KernelSpecification &"},
    {std::type_index(typeid(const KernelSpecification *)),
     "const KernelSpecification *"},
    {std::type_index(typeid(const Primitive *)), "const Primitive *"},
    {std::type_index(typeid(const Primitive &)), "const Primitive &"},
    {std::type_index(typeid(const Primitive)), "const Primitive"},
    {std::type_index(typeid(const EntropyTerm *)), "const EntropyTerm *"},
    {std::type_index(typeid(const EntropyTerm &)), "const EntropyTerm &"},
    {std::type_index(typeid(const EntropyTerm)), "const EntropyTerm"},
    {std::type_index(typeid(const PrimitiveGroup *)), "const PrimitiveGroup *"},
    {std::type_index(typeid(const PrimitiveGroup &)), "const PrimitiveGroup &"},
    {std::type_index(typeid(const PrimitiveGroup)), "const PrimitiveGroup"},
};

}
