name: Check Formatting
on: push
jobs:
  check-formatting:
    name: Check Python and C++ Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: JoshuaSBrown/cpp-py-auto-formatter/check@v0.1
      with:
        clangFormatVersion: 8
        token: ${{ secrets.GITHUB_TOKEN }}
